### PR TITLE
1.20.4

### PR DESCRIPTION
**Pull request by imthosea**
Mostly untested, especially custom recipes

### CODE REVIEW

**Comment by imthosea** [comment]
(note: now 1.20.3/1.20.4)

**Comment by Ultimategamingwaffel** [comment]
> (note: now 1.20.3/1.20.4)

Hello, 
When can you expect the 1.20.1 to come out? I'd be glad to hear that. 
Greetings

**Comment by imthosea** [comment]
> Hello, 
> 
> When can you expect the 1.20.1 to come out? I'd be glad to hear that. 
> 
> Greetings

It has been out in the [Discord server](https://discord.gg/rdrtkjJ8Va) under the #community-releases channel.

**Comment by Ultimategamingwaffel** [comment]
> > Hello,
> > When can you expect the 1.20.1 to come out? I'd be glad to hear that.
> > Greetings
> 
> It has been out in the [Discord server](https://discord.gg/rdrtkjJ8Va) under the #community-releases channel.

Thank you very much.

**Pull request merged**
